### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by 647-coder** [USTIL/Recruit-new-system#1]
1) 3.html 命名规范
2) 注意数据库用户名密码的隐藏
    1.提取到一个config文件
    2.制作成一个config_example文件来上传到github 自己密码的config文件不要上传防止泄漏
3）是否注意了防止sql注入等相关安全问题

**Comment by hapi666** [comment]
嗯嗯，我修改一下

**Comment by 647-coder** [comment]
加上部署文档, 怎么部署的, 可以的话写个sh, 自动部署.

**Comment by 647-coder** [comment]
commit 如果英文描述不好 可以用中文 不要用谜一样的描述

**Comment by hapi666** [comment]
好的
