### ISSUE TITLE
数据库用户名密码暴露了

### ISSUE THREAD

**Issue by 647-coder** [USTIL/Recruit-new-system#2]

**Comment by hapi666** [comment]
清除历史记录了，重新强制覆盖代码上去了，然后apache部署go代码我觉得不好，在服务器上裸跑go我觉得比较好，所以我就没写apache部署go的文档。

**Comment by RuanHR** [comment]
如果go启动，服务器宕机重启，项目直接部署在服务上，是不是还需要重启项目 发自网易邮箱大师 在2017年09月26日 17:50，一只傻哈皮 写道： 清除历史记录了，重新强制覆盖代码上去了，然后apache部署go代码我觉得不好，在服务器上裸跑go我觉得比较好，所以我就没写apache部署go的文档。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by hapi666** [comment]
用systemctl呀，设置一下，就能开机自启了。

**Comment by 647-coder** [comment]
要么apache 要么ngnix 请问你感觉哪里不好...
